title: RockByte Security
email: info@rockbytesec.com
# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Security Over The Rocks
baseurl: "/"
url: "https://www.rockbytesec.com/"

# Build settings

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache

repository: 0daysecured/0daysecured.github.io

google_analytics: G-MKW253DLZ8

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
